import { FileUploader } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import { Inter } from "@next/font/google";
import { Amplify, Storage } from "aws-amplify";
import Head from "next/head";
import config from "../aws-exports";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  Amplify.configure(config);

  async function onChange(e) {
    const file = e.target.files[0];
    const key = file.name;
    try {
      Storage.put(file, key, {
        level: "protected",
        contentType: "image/*",
      })
        .then((result) => console.log(result))
        .catch((err) => console.log(err));
    } catch (err) {
      console.log("error: ", err);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <input type="file" onChange={onChange} />; */}
      <FileUploader
        accept="image/*"
        variation="drop"
        isPreviewerVisible={true}
        acceptedFileTypes={["image/*"]}
        accessLevel="public"
        onSuccess={onChange}
      />
    </>
  );
}
